<a href="https://colab.research.google.com/github/DeepthiTabithaBennet/MachineLearning/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import sys

np.set_printoptions(suppress=True)
sys.stderr = object

In [ ]:
Xs = np.array([7718, 6958, 8551, 6924, 6298, 6120, 6184, 6527, 5081, 4216, 5532, 5638, 4147, 3562, 2955, 4261, 3644, 2020]) 

Xr = np.array([7258, 7232, 7062, 6526, 5251, 5158, 5051, 4850, 4825, 4762, 4750, 4620, 4229, 3497, 3480, 3392, 3120, 2946])

In [ ]:
Xs_standard = (Xs - np.mean(Xs)) / np.std(Xs, ddof=1)
print(np.sum(Xs))
print(np.sum(Xs) ** 2)
np.mean(Xs)
print(Xs_standard)


Xr_standard = (Xr - np.mean(Xr)) / np.std(Xr, ddof=1)
print(np.sum(Xr))
print(np.sum(Xr) ** 2)
np.mean(Xr)
print(Xr_standard)

96336
9280624896
[ 1.35897821  0.92245097  1.83743503  0.90292212  0.54336153  0.44112226
  0.47788245  0.67489408 -0.15565642 -0.65249334  0.10338803  0.16427209
 -0.69212542 -1.02813651 -1.37678392 -0.62664633 -0.98103752 -1.9138273 ]
88009
7745584081
[ 1.71702284  1.69817525  1.57494106  1.18639089  0.26213444  0.19471808
  0.11715303 -0.02855328 -0.04667596 -0.0923451  -0.10104398 -0.1952819
 -0.47872055 -1.00935249 -1.02167591 -1.08546773 -1.28264244 -1.40877626]


In [ ]:
cov_matrix = np.cov(Xs_standard, Xr_standard, rowvar = False)
print(cov_matrix)

[[1.         0.91561062]
 [0.91561062 1.        ]]


In [ ]:
eigen_values , eigen_vectors = np.linalg.eig(cov_matrix)
print(eigen_values)
print(eigen_vectors)

[1.91561062 0.08438938]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [ ]:
normalised_matrix = np.dstack((Xs_standard, Xr_standard))
print(normalised_matrix)

print("\n")

for i in range(0, 18):
    principal_comp = np.array([ np.dot(eigen_vectors, normalised_matrix[i].transpose()) ])
    print(principal_comp)

print("\n")

[[[ 1.35897821  1.71702284]
  [ 0.92245097  1.69817525]
  [ 1.83743503  1.57494106]
  [ 0.90292212  1.18639089]
  [ 0.54336153  0.26213444]
  [ 0.44112226  0.19471808]
  [ 0.47788245  0.11715303]
  [ 0.67489408 -0.02855328]
  [-0.15565642 -0.04667596]
  [-0.65249334 -0.0923451 ]
  [ 0.10338803 -0.10104398]
  [ 0.16427209 -0.1952819 ]
  [-0.69212542 -0.47872055]
  [-1.02813651 -1.00935249]
  [-1.37678392 -1.02167591]
  [-0.62664633 -1.08546773]
  [-0.98103752 -1.28264244]
  [-1.9138273  -1.40877626]]]


[[[-0.25317578 -0.5485199   0.18561127 -0.20044269  0.19885759
    0.17423406  0.25507422  0.4974124  -0.07706083 -0.39608462
    0.14455526  0.25424306 -0.15090003 -0.01328231 -0.25109929
    0.32443572  0.21326688 -0.35712501]
  [ 2.1750612   1.85306258  2.41291427  1.4773674   0.56957166
    0.44960702  0.42075362  0.45703196 -0.1430706  -0.52668031
    0.00165749 -0.02192724 -0.82791312 -1.44072229 -1.69596721
   -1.21064746 -1.60066345 -2.34943551]]]
